apiVersion: v1
kind: Service
metadata:
  name: my-java-webapp-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: my-java-webapp
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
